// The Android Gradle Plugin builds the native code with the Android NDK.

group 'com.famedly.flutter_vodozemac'
version '1.0'

buildscript {
    repositories {
        google()
        mavenCentral()
    }

    dependencies {
        // The Android Gradle Plugin knows how to build native code with the NDK.
        classpath 'com.android.tools.build:gradle:8.4.1'
    }
}

rootProject.allprojects {
    repositories {
        google()
        mavenCentral()
    }
}

apply plugin: 'com.android.library'

android {
    if (project.android.hasProperty("namespace")) {
        namespace 'com.famedly.flutter_vodozemac'
    }

    // Bumping the plugin compileSdkVersion requires all clients of this plugin
    // to bump the version in their app.
    compileSdkVersion 35

    // Use the NDK version
    // declared in /android/app/build.gradle file of the Flutter project.
    // Replace it with a version number if this plugin requires a specfic NDK version.
    // (e.g. ndkVersion "23.1.7779620")
    ndkVersion "27.0.12077973"

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }

    defaultConfig {
        minSdkVersion 21

        externalNativeBuild {
            // 为了支持使用 Android NDK 版本 r27 及更高版本编译 16 KB 对齐的共享库，您需要按如下方式更新 build.gradle.kts
            cmake {
                // Passes optional arguments to CMake.
                arguments "-DANDROID_SUPPORT_FLEXIBLE_PAGE_SIZES=ON"
            }
        }

    }
}

apply from: "../cargokit/gradle/plugin.gradle"
cargokit {
    manifestDir = "../rust"
    libname = "flutter_vodozemac"
}
